[project]
name = "kaggle-past-competitions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kaggle>=1.8.2",
    "marimo>=0.18.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
